version: '3.8'

services:
  gateway:
    image: ggstudy11/kg-gateway:latest  # 使用 Docker Hub 的用户名 + 镜像名
    build:
      context: ./gateway
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      - JAVA_OPTS=-Xms256m -Xmx512m -XX:+UseG1GC
    networks:
      - app-network

  user-service:
    image: ggstudy11/kg-userservice:latest  # 使用 Docker Hub 的用户名 + 镜像名
    build:
      context: ./user-service
      dockerfile: Dockerfile
    ports:
      - "8081:8081"
    environment:
      - JAVA_OPTS=-Xms256m -Xmx512m -XX:+UseG1GC
    networks:
      - app-network

  file-service:
    image: ggstudy11/kg-fileservice:latest  # 使用 Docker Hub 的用户名 + 镜像名
    build:
      context: ./file-service
      dockerfile: Dockerfile
    ports:
      - "8082:8082"
    environment:
      - JAVA_OPTS=-Xms256m -Xmx512m -XX:+UseG1GC
    networks:
      - app-network

  blog-service:
    image: ggstudy11/kg-blogservice:latest  # 使用 Docker Hub 的用户名 + 镜像名
    build:
      context: ./blog-service
      dockerfile: Dockerfile
    ports:
      - "8083:8083"
    environment:
      - JAVA_OPTS=-Xms256m -Xmx512m -XX:+UseG1GC
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
