server:
  port: 8080

springdoc:
  api-docs:
    path: /v1/api-docs # API 文档路径
  swagger-ui:
    path: /swagger-ui.html # Swagger UI 路径

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: 07030877
    url: jdbc:mysql://8.153.102.70:3306/know_graph?useUnicode=true&characterEncoding=UTF-8&autoReconnect=true&serverTimezone=UTC